### ISSUE TITLE
redis_nginx_adapter/missing: line 81: aclocal-1.14: command not found

### ISSUE THREAD

**Issue by dowson521** [wandenberg/redis_nginx_adapter#2]
i try to make this packages, it's raise an error like this:

CDPATH="${ZSH_VERSION+.}:" && cd . && /bin/sh /home/packages/redis_nginx_adapter/missing aclocal-1.14
/home/packages/redis_nginx_adapter/missing: line 81: aclocal-1.14: command not found
WARNING: 'aclocal-1.14' is missing on your system.
         You should only need it if you modified 'acinclude.m4' or
         'configure.ac' or m4 files included by 'configure.ac'.
         The 'aclocal' program is part of the GNU Automake package:
         http://www.gnu.org/software/automake
         It also requires GNU Autoconf, GNU m4 and Perl in order to run:
         http://www.gnu.org/software/autoconf
         http://www.gnu.org/software/m4/
         http://www.perl.org/
could you tell what happened.....thanks very much..

btw..my server os is CentOS 6.3 64bit

**Comment by gp187** [comment]
The problem is the `automake` package installs `aclocal-1.13`or `aclocal-1.14` You need to target the exact version you need. Use this script and compile with the versions you need 

```

VERSION=1.15
    wget ftp://ftp.gnu.org/gnu/automake/automake-${VERSION}.tar.gz &> /dev/null
    if [ -f "automake-${VERSION}.tar.gz" ]; then
            tar -xzf automake-${VERSION}.tar.gz
            cd automake-${VERSION}/
            ./configure
            make && make install
            echo -e "\e[1;39m[   \e[1;32mOK\e[39m   ] automake-${VERSION} installed\e[0;39m"

        else
            echo -e "\e[1;39m[   \e[31mError\e[39m   ] cannot fetch file from ftp://ftp.gnu.org/gnu/automake/ \e[0;39m"
            exit 1
fi
```
