### ISSUE TITLE
Pool Connection

### ISSUE THREAD

**Issue by pradeepitm12** [wandenberg/redis_nginx_adapter#3]
I a redis pool connection which is live till the nginx server is live. and one thread for a single worker.
Need suggestion on this.
Currently  following ur guid and  got this error undefined reference to `redis_nginx_init', undefined reference to `redis_nginx_open_context', undefined reference to `redisAsyncCommand', undefined reference to `redis_nginx_close_context'

**Comment by wandenberg** [comment]
@pradeepitm12 had you solved your issue?
From the message you wrote seems that you are not properly linking your module to the library.
